### ISSUE TITLE
It is not work

### ISSUE THREAD

**Issue by LiuWeiMr** [dynamsoft-dwt/vue-document-scan-load-readBarcode#1]
![image](https://user-images.githubusercontent.com/17976666/76722276-d926e800-677d-11ea-8388-4f7969209f41.png)
There are nine error when run : npm run serve.

**Comment by Tom-Dynamsoft** [comment]
@LiuWeiMr  Sorry for the delay. THis sample is outdated, please check out https://github.com/dynamsoft-dwt/dwt-vue-simple to get it working first. thx
