### ISSUE TITLE
i get ResourcesPath

### ISSUE THREAD

**Issue by b23618** [dynamsoft-dwt/vue-document-scan-load-readBarcode#2]
`Dynamsoft.DWT.ResourcesPath = "dwt-resources" `

packege.json
`    "scripts": {
        "dev": "ncp node_modules/dwt/dist static/dwt-resources && nuxt",
        "build": "nuxt build",
        "start": "nuxt start",
        "generate": "nuxt generate && ncp node_modules/dwt/dist dist/dwt-resources"
    },`

i use framwork nuxt js but error get path dwt-resources 
help me please!!!

**Comment by lincoln2018** [comment]
packege.json
"scripts": { "dev": "ncp node_modules/dwt/dist static/dwt-resources && nuxt", "build": "nuxt build", "start": "nuxt start", "generate": "nuxt generate && ncp node_modules/dwt/dist **static**/dwt-resources" },

change "dist/dwt-resources" to "static/dwt-resources" in packege.json,  rebuild

ref url: https://nuxtjs.org/docs/2.x/directory-structure/static/
